# Generated by Django 3.2.23 on 2024-01-25 06:33

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=users.models.AchievementType.get_path, verbose_name='Обложка')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('points', models.IntegerField(verbose_name='Баллы')),
                ('achievement_type_name', models.CharField(max_length=255, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип достижения',
                'verbose_name_plural': 'Типы достижений',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.IntegerField(default=0, verbose_name='Прогресс сейчас')),
                ('total_progress', models.IntegerField(default=0, verbose_name='Прогресс всего')),
                ('achievement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_achievementtype', to='users.achievementtype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='achievements',
            field=models.ManyToManyField(related_name='users_achievement', to='users.Achievement', verbose_name='Достижения'),
        ),
    ]
