# Generated by Django 3.2.23 on 2024-01-16 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240114_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default=datetime.date(2024, 1, 16), verbose_name='Дата'),
        ),
    ]
