# Generated by Django 3.2.23 on 2024-01-20 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default=datetime.date(2024, 1, 20), verbose_name='День рождения'),
        ),
    ]
