# Generated by Django 3.2.23 on 2024-01-17 08:21

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import proposals.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Уровень')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 17, 13, 21, 11, 73307), verbose_name='Дата')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('status_type', models.CharField(max_length=255, verbose_name='Тип статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.JSONField(verbose_name='Содержание')),
                ('document', models.FileField(upload_to=proposals.models.Proposal.get_path, verbose_name='Файл документа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2024, 1, 17, 13, 21, 11, 73750), verbose_name='Дата создания')),
                ('author', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_category', to='proposals.category', verbose_name='Категория')),
                ('histories', models.ManyToManyField(related_name='proposals_history', to='proposals.History', verbose_name='История')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories_status', to='proposals.status', verbose_name='Статус'),
        ),
    ]
