# Generated by Django 3.2.23 on 2024-01-17 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 17, 13, 22, 7, 807904), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 13, 22, 7, 808370), verbose_name='Дата создания'),
        ),
    ]
