# Generated by Django 3.2.23 on 2024-01-17 08:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_remove_history_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 17, 13, 24, 31, 508710), verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='history',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Уровень'),
        ),
    ]
