# Generated by Django 3.2.23 on 2024-01-17 08:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_auto_20240117_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='level',
        ),
        migrations.AddField(
            model_name='proposal',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 17, 13, 32, 57, 434499), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 13, 32, 57, 434960), verbose_name='Дата создания'),
        ),
    ]
