# Generated by Django 3.2.23 on 2024-01-19 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_auto_20240119_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 16, 52, 34, 726999), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 19, 16, 52, 34, 725470), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 16, 52, 34, 725975), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='proposalpost',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='proposalposts_comment', to='proposals.Comment', verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='proposalpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='proposalposts_tag', to='proposals.Tag', verbose_name='Тэги'),
        ),
    ]
