# Generated by Django 3.2.23 on 2024-01-24 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0021_auto_20240125_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 1, 5, 38, 114535), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 25, 1, 5, 38, 113068), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 1, 5, 38, 113524), verbose_name='Дата создания'),
        ),
    ]
