# Generated by Django 3.2.23 on 2024-01-24 21:30

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0022_auto_20240125_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 2, 30, 16, 805420), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 25, 2, 30, 16, 803936), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 2, 30, 16, 804417), verbose_name='Дата создания'),
        ),
        migrations.RemoveField(
            model_name='proposalpost',
            name='likes',
        ),
        migrations.AddField(
            model_name='proposalpost',
            name='likes',
            field=models.ManyToManyField(related_name='proposals_like', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
