# Generated by Django 3.2.23 on 2024-01-25 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0026_auto_20240125_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 11, 34, 43, 764028), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 25, 11, 34, 43, 762489), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 11, 34, 43, 762928), verbose_name='Дата создания'),
        ),
    ]
