# Generated by Django 3.2.23 on 2024-01-26 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0027_auto_20240125_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 13, 54, 59, 398138), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 26, 13, 54, 59, 396545), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 13, 54, 59, 397000), verbose_name='Дата создания'),
        ),
    ]
