# Generated by Django 3.2.23 on 2024-01-25 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=255, verbose_name='КПП')),
                ('ogrn', models.CharField(max_length=255, verbose_name='ОГРН')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('created_date', models.DateField(default=datetime.date(2024, 1, 25), verbose_name='Дата создрания')),
                ('scope', models.TextField(verbose_name='Основная деятельность')),
            ],
            options={
                'verbose_name': 'Компния',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='ОПисание')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('creation_date', models.DateField(default=datetime.date(2024, 1, 25), verbose_name='Дата создрания')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('departments', models.ManyToManyField(blank=True, related_name='offices_department', to='companies.Department', verbose_name='Департаменты')),
            ],
            options={
                'verbose_name': 'Офис',
                'verbose_name_plural': 'Офисы',
            },
        ),
    ]
