# Generated by Django 3.2.23 on 2024-01-25 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='heads',
            field=models.ManyToManyField(related_name='offices_head', to=settings.AUTH_USER_MODEL, verbose_name='Руководители'),
        ),
        migrations.AddField(
            model_name='division',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='divisions_employee', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='division',
            name='heads',
            field=models.ManyToManyField(blank=True, related_name='divisions_head', to=settings.AUTH_USER_MODEL, verbose_name='Руководители'),
        ),
        migrations.AddField(
            model_name='department',
            name='divisions',
            field=models.ManyToManyField(blank=True, related_name='departments_division', to='companies.Division', verbose_name='Отделы'),
        ),
        migrations.AddField(
            model_name='department',
            name='heads',
            field=models.ManyToManyField(related_name='departments_head', to=settings.AUTH_USER_MODEL, verbose_name='Руководители'),
        ),
        migrations.AddField(
            model_name='company',
            name='ceo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_ceo', to=settings.AUTH_USER_MODEL, verbose_name='СЕО'),
        ),
        migrations.AddField(
            model_name='company',
            name='jobs',
            field=models.ManyToManyField(related_name='companies_job', to='users.Job', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='company',
            name='offices',
            field=models.ManyToManyField(related_name='companies_office', to='companies.Office', verbose_name='Офисы'),
        ),
    ]
