# Generated by Django 3.2.23 on 2024-01-13 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='employees',
            field=models.ManyToManyField(related_name='divisions_employee', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='division',
            name='heads',
            field=models.ManyToManyField(related_name='divisions_head', to=settings.AUTH_USER_MODEL, verbose_name='Руководители'),
        ),
        migrations.AddField(
            model_name='department',
            name='heads',
            field=models.ManyToManyField(related_name='departments_head', to=settings.AUTH_USER_MODEL, verbose_name='Руководители'),
        ),
    ]
