# Generated by Django 3.2.23 on 2024-01-16 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0003_alter_office_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='divisions',
            field=models.ManyToManyField(related_name='departments_division', to='companies.Department', verbose_name='Отделы'),
        ),
        migrations.AddField(
            model_name='office',
            name='heads',
            field=models.ManyToManyField(related_name='offices_head', to=settings.AUTH_USER_MODEL, verbose_name='Руководители'),
        ),
    ]
