# Generated by Django 3.2.23 on 2024-01-16 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20240116_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='creation_date',
            field=models.DateField(default=datetime.date(2024, 1, 17), verbose_name='Дата создрания'),
        ),
    ]
