# Generated by Django 3.2.23 on 2024-01-17 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0005_alter_office_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='divisions',
            field=models.ManyToManyField(blank=True, related_name='departments_division', to='companies.Department', verbose_name='Отделы'),
        ),
        migrations.AlterField(
            model_name='division',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='divisions_employee', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='office',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='offices_department', to='companies.Department', verbose_name='Департаменты'),
        ),
    ]
