# Generated by Django 3.2.23 on 2024-01-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20240117_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='divisions',
            field=models.ManyToManyField(blank=True, related_name='departments_division', to='companies.Division', verbose_name='Отделы'),
        ),
    ]
