# Generated by Django 3.2.23 on 2024-01-18 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_department_divisions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterField(
            model_name='office',
            name='creation_date',
            field=models.DateField(default=datetime.date(2024, 1, 18), verbose_name='Дата создрания'),
        ),
    ]
