# Generated by Django 3.2.23 on 2024-01-19 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20240118_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='creation_date',
            field=models.DateField(default=datetime.date(2024, 1, 19), verbose_name='Дата создрания'),
        ),
    ]
