# Generated by Django 3.2.23 on 2024-01-19 11:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_alter_customuser_birthday'),
        ('companies', '0009_alter_office_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=255, verbose_name='КПП')),
                ('ogrn', models.CharField(max_length=255, verbose_name='ОГРН')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('created_date', models.DateField(default=datetime.date(2024, 1, 19), verbose_name='Дата создрания')),
                ('scope', models.TextField(verbose_name='Основная деятельность')),
                ('ceo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_ceo', to=settings.AUTH_USER_MODEL, verbose_name='СЕО')),
                ('jobs', models.ManyToManyField(related_name='companies_job', to='users.Job', verbose_name='Должность')),
                ('offices', models.ManyToManyField(related_name='companies_office', to='companies.Office', verbose_name='Офисы')),
            ],
            options={
                'verbose_name': 'Компния',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
