# Generated by Django 3.2.23 on 2024-01-19 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0010_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='heads',
            field=models.ManyToManyField(blank=True, related_name='divisions_head', to=settings.AUTH_USER_MODEL, verbose_name='Руководители'),
        ),
    ]
