# Generated by Django 3.2.23 on 2024-01-20 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_division_heads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 1, 20), verbose_name='Дата создрания'),
        ),
        migrations.AlterField(
            model_name='office',
            name='creation_date',
            field=models.DateField(default=datetime.date(2024, 1, 20), verbose_name='Дата создрания'),
        ),
    ]
